name: fit_wallet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  equatable: ^2.0.5
  sqflite: ^2.4.0
  go_router: ^14.3.0
  freezed: ^2.5.7
  shared_preferences: ^2.3.2
  flex_color_scheme: ^7.3.1
  auto_size_text: ^3.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: lib\assets\fonts\NotoSans-Regular.ttf
        - asset: lib\assets\fonts\NotoSans-Italic.ttf
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
