import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

sealed class AppTheme {
  // The defined light theme.
  static ThemeData light = FlexThemeData.light(
    fontFamily: 'NotoSans',
    scheme: FlexScheme.jungle,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnLevel: 25,
      scaffoldBackgroundBaseColor: FlexScaffoldBaseColor.surface,
      useM2StyleDividerInM3: true,
      thinBorderWidth: 1.5,
      textButtonRadius: 15.0,
      filledButtonRadius: 15.0,
      elevatedButtonRadius: 15.0,
      elevatedButtonSecondarySchemeColor: SchemeColor.surfaceContainer,
      outlinedButtonRadius: 15.0,
      toggleButtonsRadius: 13.0,
      toggleButtonsBorderWidth: 1.0,
      segmentedButtonRadius: 15.0,
      segmentedButtonBorderWidth: 1.0,
      inputDecoratorIsFilled: true,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 15.0,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorFocusedBorderWidth: 1.5,
      popupMenuRadius: 8.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      dialogRadius: 20.0,
      snackBarRadius: 4,
      drawerRadius: 15.0,
      drawerIndicatorRadius: 15.0,
      menuBarRadius: 0.0,
      searchBarRadius: 15.0,
      searchViewRadius: 15.0,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
  // The defined dark theme.
  static ThemeData dark = FlexThemeData.dark(
    fontFamily: 'NotoSans',
    scheme: FlexScheme.jungle,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      thinBorderWidth: 1.5,
      textButtonRadius: 15.0,
      filledButtonRadius: 15.0,
      elevatedButtonRadius: 15.0,
      elevatedButtonSecondarySchemeColor: SchemeColor.surfaceContainer,
      outlinedButtonRadius: 15.0,
      toggleButtonsRadius: 13.0,
      toggleButtonsBorderWidth: 1.0,
      segmentedButtonRadius: 15.0,
      segmentedButtonBorderWidth: 1.0,
      inputDecoratorIsFilled: true,
      inputDecoratorBackgroundAlpha: 128,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 15.0,
      inputDecoratorBorderWidth: 0.5,
      inputDecoratorFocusedBorderWidth: 1.5,
      popupMenuRadius: 8.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      dialogRadius: 20.0,
      snackBarRadius: 4,
      drawerRadius: 15.0,
      drawerIndicatorRadius: 15.0,
      menuBarRadius: 0.0,
      searchBarRadius: 15.0,
      searchViewRadius: 15.0,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
  );
}
